# tf.argmax and tf.reduce_max
 
Sungchul Lee  

# How to run these slides yourself

**Setup python environment**

- [Install RISE for an interactive presentation viewer](https://github.com/damianavila/RISE)

# tf.argmax (tf.argmin)

> For each row, find argmax.

> The rank is down by 1.

```
tf.argmax(
    input,
    axis=None,
    name=None,
    dimension=None,
    output_type=tf.int64
)
```

https://www.tensorflow.org/api_docs/python/tf/argmax

In [8]:
import tensorflow as tf

t = tf.constant([[1, 8, 3], 
                 [4, 7, 6], 
                 [9, 2, 5]])

if 0:
    # 각각의 칼럼에서 최대값이 발생하는 인덱스를 찿음
    argmax_where = tf.argmax(t) 
elif 0:
    argmax_where = tf.argmax(t, output_type=tf.int32) 
elif 0:
    # 각각의 칼럼에서 최대값이 발생하는 인덱스를 찿음
    argmax_where = tf.argmax(t, axis=0)
elif 0:
    argmax_where = tf.argmax(t, axis=0, output_type=tf.int32)
elif 0:
    # 각각의 로에서 최대값이 발생하는 인덱스를 찿음
    argmax_where = tf.argmax(t, axis=1)
elif 1:
    argmax_where = tf.argmax(t, axis=1, output_type=tf.int32)

with tf.Session() as sess:
    print(sess.run(argmax_where))
    print(sess.run(argmax_where).dtype)

[1 1 0]
int32


# tf.reduce_max (tf.reduce_min)

> For each row, find max

> The rank is down by 1. 

> You can use 'keepdims=True' to keep the current rank.

```
tf.reduce_max(
    input_tensor,
    axis=None,
    keepdims=None,
    name=None,
    reduction_indices=None
)
```

https://www.tensorflow.org/versions/r1.8/api_docs/python/tf/reduce_max

In [11]:
import tensorflow as tf

t = tf.constant([[1, 8, 3], 
                 [4, 7, 6], 
                 [9, 2, 5]])

if 0:
    # 최대값 찿음
    M = tf.reduce_max(t) 
elif 0:
    # 각각의 칼럼에서 최대값 찿음
    M = tf.reduce_max(t, axis=0)
elif 1:
    # 각각의 로에서 최대값 찿음
    M = tf.reduce_max(t, axis=1)

with tf.Session() as sess:
    print(sess.run(M))

[8 7 9]


# keepdims=True

In [14]:
import tensorflow as tf

t = tf.constant([[1, 8, 3], 
                 [4, 7, 6], 
                 [9, 2, 5]])

if 0:
    # 최대값 찿음
    M = tf.reduce_max(t, keepdims=True) 
elif 0:
    # 각각의 칼럼에서 최대값 찿음
    M = tf.reduce_max(t, axis=0, keepdims=True)
elif 1:
    # 각각의 로에서 최대값 찿음
    M = tf.reduce_max(t, axis=1, keepdims=True)

with tf.Session() as sess:
    print(sess.run(M))

[[8]
 [7]
 [9]]
