# tf.one_hot
 
Sungchul Lee  

# How to run these slides yourself

**Setup python environment**

- [Install RISE for an interactive presentation viewer](https://github.com/damianavila/RISE)

```
tf.one_hot(
    indices,
    depth,
    on_value=None,
    off_value=None,
    axis=None,
    ype=None,
    name=None
)
```

dthttps://www.tensorflow.org/versions/r1.8/api_docs/python/tf/one_hot

In [1]:
import tensorflow as tf

a = tf.one_hot([0, 1, 2, 1], 5)
b = tf.one_hot([0, 1, 2, 1], 10)

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
