In [9]:
import tensorflow as tf
import numpy as np
tf.reset_default_graph()
tf.set_random_seed(0)
np.random.seed(0)

x_data = np.array([[1.],[2.],[3.],[4.]]).astype(np.float32) # (4,1)
y_data = np.array([[1.],[2.],[3.],[4.]]).astype(np.float32) # (4,1)

x = tf.placeholder(tf.float32, (None,1)) # (4,1)
y = tf.placeholder(tf.float32, (None,1)) # (4,1)

alpha = tf.get_variable('alpha', (), tf.float32, tf.keras.initializers.zeros())
beta = tf.get_variable('beta', (), tf.float32, tf.keras.initializers.ones())

y_pred = alpha + beta * x
loss = tf.reduce_mean((y-y_pred)**2)

with tf.Session() as sess:
    
    tf.global_variables_initializer().run()
    
    feed_dict = {x:x_data, y:y_data}
    y_pred_run, loss_run = sess.run([y_pred, loss], feed_dict=feed_dict)
    print(y_pred_run, loss_run) 

[[1.]
 [2.]
 [3.]
 [4.]] 0.0


In [10]:
import tensorflow as tf
import numpy as np
tf.reset_default_graph()
tf.set_random_seed(0)
np.random.seed(0)

x_data = np.array([[1.],[2.],[3.],[4.]]).astype(np.float32) # (4,1)
y_data = np.array([[1.],[2.],[3.],[4.]]).astype(np.float32) # (4,1)

x = tf.placeholder(tf.float32, (None,1)) # (4,1)
y = tf.placeholder(tf.float32, (None,1)) # (4,1)

alpha = tf.get_variable('alpha', (), tf.float32, tf.keras.initializers.zeros())
beta = tf.get_variable('beta', (), tf.float32, tf.keras.initializers.ones())

y_pred = alpha + beta * x
loss = tf.reduce_mean((y-y_pred)**2)

with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    
    feed_dict = {x:x_data, y:y_data}
    y_pred_run, loss_run = sess.run([y_pred, loss], feed_dict=feed_dict)
    print(y_pred_run, loss_run) 

[[1.]
 [2.]
 [3.]
 [4.]] 0.0


In [14]:
import tensorflow as tf
import numpy as np
tf.reset_default_graph()
tf.set_random_seed(0)
np.random.seed(0)

x_data = np.array([[1.],[2.],[3.],[4.]]).astype(np.float32) # (4,1)
y_data = np.array([[1.],[2.],[3.],[4.]]).astype(np.float32) # (4,1)

x = tf.placeholder(tf.float32, (None,1)) # (4,1)
y = tf.placeholder(tf.float32, (None,1)) # (4,1)

alpha = tf.get_variable('alpha', (), tf.float32, tf.keras.initializers.zeros())
beta = tf.get_variable('beta', (), tf.float32, tf.keras.initializers.ones())

y_pred = alpha + beta * x
loss = tf.reduce_mean((y-y_pred)**2)

with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    
    feed_dict = {x:x_data}
    y_pred_run = sess.run(y_pred, feed_dict=feed_dict)
    print(y_pred_run) 

[[1.]
 [2.]
 [3.]
 [4.]]


In [15]:
import tensorflow as tf
import numpy as np
tf.reset_default_graph()
tf.set_random_seed(0)
np.random.seed(0)

x_data = np.array([[1.],[2.],[3.],[4.]]).astype(np.float32) # (4,1)
y_data = np.array([[1.],[2.],[3.],[4.]]).astype(np.float32) # (4,1)

x = tf.placeholder(tf.float32, (None,1)) # (4,1)
y = tf.placeholder(tf.float32, (None,1)) # (4,1)

alpha = tf.get_variable('alpha', (), tf.float32, tf.keras.initializers.zeros())
beta = tf.get_variable('beta', (), tf.float32, tf.keras.initializers.ones())

y_pred = alpha + beta * x
loss = tf.reduce_mean((y-y_pred)**2)

with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    
    feed_dict = {x:x_data, y:y_data}
    loss_run = sess.run(loss, feed_dict=feed_dict)
    print(loss_run)

0.0
